// Registry of bundled OFL fonts (vendor/fonts/<key>/). Build copies the ones a site lists
// and generates assets/css/fonts.css from this table.

const AR = 'U+0600-06FF, U+0750-077F, U+0870-088E, U+0890-0891, U+0898-08E1, U+08E3-08FF, U+200C-200E, U+2010-2011, U+204F, U+2E41, U+FB50-FDFF, U+FE70-FE74, U+FE76-FEFC';
const LA = 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD';

const perWeight = (family, prefix, weights, subsets = ['arabic', 'latin']) =>
  weights.flatMap((w) =>
    subsets.map((s) => ({ family, file: `${prefix}-${s}-${w}-normal.woff2`, weight: String(w), range: s === 'arabic' ? AR : LA }))
  );

export const FONTS = {
  vazirmatn: [{ family: 'Vazirmatn', file: 'Vazirmatn-wght.woff2', weight: '100 900' }],
  estedad: perWeight('Estedad', 'estedad', [300, 400, 500, 700, 800, 900]),
  lalezar: perWeight('Lalezar', 'lalezar', [400]),
  'reem-kufi': perWeight('Reem Kufi', 'reem-kufi', [400, 700]),
  'noto-nastaliq': perWeight('Noto Nastaliq Urdu', 'noto-nastaliq-urdu', [400, 700], ['arabic']),
  markazi: [
    { family: 'Markazi Text', file: 'markazi-text-arabic-wght-normal.woff2', weight: '400 700', range: AR },
    { family: 'Markazi Text', file: 'markazi-text-latin-wght-normal.woff2', weight: '400 700', range: LA },
  ],
  'noto-kufi': [
    { family: 'Noto Kufi Arabic', file: 'noto-kufi-arabic-arabic-wght-normal.woff2', weight: '100 900', range: AR },
    { family: 'Noto Kufi Arabic', file: 'noto-kufi-arabic-latin-wght-normal.woff2', weight: '100 900', range: LA },
  ],
};

export function fontFaceCss(keys) {
  const out = ['/* Generated by tools/build.mjs. Fonts are SIL OFL 1.1 licensed; see /licenses. */'];
  for (const key of keys) {
    for (const f of FONTS[key]) {
      out.push(
        `@font-face {\n  font-family: '${f.family}';\n  src: url('../fonts/${key}/${f.file}') format('woff2');\n  font-weight: ${f.weight};\n  font-style: normal;\n  font-display: swap;${f.range ? `\n  unicode-range: ${f.range};` : ''}\n}`
      );
    }
  }
  return out.join('\n\n') + '\n';
}
